### ISSUE TITLE
Svelte Adders

### ISSUE THREAD

**Issue by benmccann** [robole/svelte-vite-jest-template#1]
Hey Rob, thanks for putting this together! I wanted to see if you're familiar with Svelte Adders? We're trying to make that the go-to way to setup integrations with various things like testing libraries. Templates get tricky when you want to mix-and-match technologies, but with Svelte Adders you can run multiple to add multiple technologies

There's an adder for Jest: https://github.com/rossyman/svelte-add-jest. I haven't fully gotten to take a look at everything you've done here, but we could use some smart people collaborating on the testing story, so I wanted to share and see if you have any feedback!

**Comment by robole** [comment]
hi @benmccann 

i havent used sveltekit, so i am not familiar with adders. i have only used svelte on its own. 

on a recent project, I tried svelte with vite instead of rollup, and this template came from that. i wrote about it in this article: [Testing a Svelte app with Jest](https://www.roboleary.net/2021/11/18/svelte-app-testing-jest.html). you can give it a read if you want to. it was an unpleasant experience! in the end I found it easier to make a small Todo app to try to test something 100% and work out the kinks.

for sure, there is a great need to improve integration of frontend dev tools. people are building their own version of the same things continually to realise marginal gains, which contributes to compatibility issues again and again. my own finding was that jest is not a good fit to use with vite unless vite improves integration/jest supports ESM 100%.  It may get stuck in the middle. A testing framework written in ESM would be a better fit.

i am interested in the way things are going, but i cant invest time into supporting the new frontiers. i think i would find it too frustrating, when the biggest issue appears to be a [coordination problem within the developer economy](https://bizfluent.com/info-8361510-definition-coordination-problems-economics.html). I support open source, but I pick my battles very carefully!

if i get to sveltekit later, i may add my 2 cents.

all the best
